var cityJobs = [
  {
   "Job_listing_id": 1,
    "City_id": "35",
    "title": "teacher",
    "sector": "education",
    "edu_req": "college",
    "lang_req": "english",
    "salary_min": "-",
    "salary_max": "-",
    "benefits": "-",
    "hyperlink": "https://vn.indeed.com/cmp/Trung-t%C3%A2m-ngo%E1%BA%A1i-ng%E1%BB%AF-Ms-Th%C6%A1m/jobs/Gi%C3%A1o-Vi%C3%AAn-a216ed6e3a1f8b76?vjs=3",
    "search_provider": "indeed.vn"
  },
  {
    "Job_listing_id": "2",
    "City_id": "35",
    "title": "factory worker",
    "sector": "shipping",
    "edu_req": "-",
    "lang_req": "-",
    "salary_min": "8000000",
    "salary_max": "1000000",
    "benefits": "health insurance",
    "hyperlink": "https://vn.indeed.com/viewjob?jk=04ee92089a25e108&tk=1c9dg798r0tht33u&from=serp&vjs=3",
    "search_provider": "indeed.vn"
  },
  {
    "Job_listing_id": "3",
    "City_id": "35",
    "title": "sales accountant",
    "sector": "jewellery",
    "edu_req": "-",
    "lang_req": "-",
    "salary_min": "4500000",
    "salary_max": "6",
    "benefits": "500",
    "hyperlink": "000 ",
    "search_provider": "insurance"
  },
  {
    "Job_listing_id": "4",
    "City_id": "52",
    "title": "real estate business staff",
    "sector": "real estate",
    "edu_req": "-",
    "lang_req": "-",
    "salary_min": "-",
    "salary_max": "-",
    "benefits": "-",
    "hyperlink": "https://vn.indeed.com/viewjob?jk=49661c7b8ce9684e&tk=1c9dcqrmm0tht6bd&from=serp&vjs=3",
    "search_provider": "indeed.vn"
  },
  {
    "Job_listing_id": "5",
    "City_id": "52",
    "title": "mine accountant",
    "sector": "mining",
    "edu_req": "university",
    "lang_req": "-",
    "salary_min": "6000000",
    "salary_max": "8000000",
    "benefits": "insurance",
    "hyperlink": " lunch allowance",
    "search_provider": "https://vn.indeed.com/viewjob?jk=e905804a6116590d&tk=1c9dggk700tht2ec&from=serp&vjs=3"
  },
  {
    "Job_listing_id": "6",
    "City_id": "52",
    "title": "sales executive",
    "sector": "-",
    "edu_req": "university",
    "lang_req": "-",
    "salary_min": "-",
    "salary_max": "-",
    "benefits": "-",
    "hyperlink": "https://vn.indeed.com/viewjob?jk=10d45bad2772d4a3&tk=1c9dggk700tht2ec&from=serp&vjs=3",
    "search_provider": "indeed.vn"
  },
  {
    "Job_listing_id": "7",
    "City_id": "52",
    "title": "direct sales executive",
    "sector": "consumer goods",
    "edu_req": "high school",
    "lang_req": "-",
    "salary_min": "6744853",
    "salary_max": "9744853",
    "benefits": "-",
    "hyperlink": "https://vn.indeed.com/viewjob?jk=c50f25e3afa902e8&tk=1c9dggk700tht2ec&from=serp&vjs=3",
    "search_provider": "indeed.vn"
  },
  {
    "Job_listing_id": "8",
    "City_id": "52",
    "title": "sales engineer",
    "sector": "-",
    "edu_req": "-",
    "lang_req": "-",
    "salary_min": "-",
    "salary_max": "-",
    "benefits": "-",
    "hyperlink": "https://vn.indeed.com/viewjob?jk=e4fc76f42bbb4505&tk=1c9dhcgmm0tht1f7&from=serp&vjs=3",
    "search_provider": "indeed.vn"
  },
  {
    "Job_listing_id": "9",
    "City_id": "25",
    "title": "Accountant of FPT Repository Lao Cai ",
    "sector": "telecommunications",
    "edu_req": "college",
    "lang_req": "-",
    "salary_min": "5000000",
    "salary_max": "7000000",
    "benefits": "-",
    "hyperlink": "https://vn.indeed.com/viewjob?jk=544ff40f91e474c4&tk=1c9dhgq7h0tht25r&from=serp&vjs=3",
    "search_provider": "indeed.vn"
  },
  {
    "Job_listing_id": "10",
    "City_id": "25",
    "title": "logistics officer",
    "sector": "logistics",
    "edu_req": "university",
    "lang_req": "-",
    "salary_min": "6000000",
    "salary_max": "9000000",
    "benefits": "insurance",
    "hyperlink": "https://vn.indeed.com/viewjob?jk=14d94d8d95ab1cbc&tk=1c9dhk5ot0tht0sf&from=serp&vjs=3",
    "search_provider": "indeed.vn"
  },
  {
    "Job_listing_id": "11",
    "City_id": "25",
    "title": "business consultant",
    "sector": "insurance",
    "edu_req": "college",
    "lang_req": "-",
    "salary_min": "-",
    "salary_max": "-",
    "benefits": "-",
    "hyperlink": "https://vn.indeed.com/viewjob?jk=13da93de5c3cb1f1&tk=1c9dhn64s0tht6l2&from=serp&vjs=3",
    "search_provider": "indeed.vn"
  },
  {
    "Job_listing_id": "12",
    "City_id": "25",
    "title": "restaurant manager",
    "sector": "food and beverage",
    "edu_req": "college",
    "lang_req": "-",
    "salary_min": "-",
    "salary_max": "-",
    "benefits": "-",
    "hyperlink": "https://vn.indeed.com/cmp/CN-C%C3%94NG-TY-TNHH-LOTTERIA-VI%E1%BB%86T-NAM/jobs/Qu%E1%BA%A3n-L%C3%BD-Nh%C3%A0-H%C3%A0ng-17689c12c9188d23?vjs=3",
    "search_provider": "indeed.vn"
  },
  {
    "Job_listing_id": ""
  }
]
